apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hpa.yaml
  - deployment.yaml
  - service.yaml
namespace: ping
patches:
  - path: ingress-patch.yaml
    target:
      kind: Service
      name: podinfo
      namespace: ping
      version: v1
